### ISSUE TITLE
Grouped Feeds/Query Feeds?

### ISSUE THREAD

**Issue by jhilker98** [stefandtw/feedranger#2]
Hi there, I just discovered feedranger today and have really been enjoying using it. However, with my main RSS reader Newsboat, I am able to group feeds and contain feeds that have a certain tag. Would anything like this be possible in feedranger, or is it out of the scope of the project?

Thanks again for making this software. :)

**Comment by stefandtw** [comment]
I would put this in the "personal customization" category. Something that isn't a core feature, but hopefully feasible to implement as a user.

Here is one way to do it:

* Add tag names as part of the feed names, like `Feed XYZ (football, sports)`
* Execute `:filter football` when you're viewing the feed list

You could map such a command to a key binding for each tag you use.

Maybe not the most elegant solution, but easy to do.

**Comment by jhilker98** [comment]
Thanks!
